const ItemActionTypes = {
	FETCH_ITEMS_START: 'FETCH_ITEMS_START',
	FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
	FETCH_ITEM_DETAIL_START: 'FETCH_ITEM_DETAIL_START',
	FETCH_ITEM_DETAIL_SUCCESS: 'FETCH_ITEM_DETAIL_SUCCESS',
	FETCH_FAILURE: 'FETCH_FAILURE',
};

export default ItemActionTypes;
